"""
IBM watsonx.ai Granite integration service.
Uses ibm-watsonx-ai Python SDK with ibm/granite-3-3-8b-instruct.
Falls back gracefully to mock responses when credentials are not configured.
"""
from typing import Optional
from app.core.config import settings

_model = None


def _get_model():
    global _model
    if _model is not None:
        return _model
    if not settings.WATSONX_API_KEY or not settings.WATSONX_PROJECT_ID:
        return None
    try:
        from ibm_watsonx_ai.foundation_models import ModelInference
        _model = ModelInference(
            model_id=settings.WATSONX_MODEL_ID,
            credentials={
                "apikey": settings.WATSONX_API_KEY,
                "url": settings.WATSONX_URL,
            },
            project_id=settings.WATSONX_PROJECT_ID,
        )
        return _model
    except Exception as e:
        print(f"[watsonx] Failed to initialise model: {e}")
        return None


def generate(prompt: str) -> str:
    """Generate text using IBM watsonx.ai Granite. Returns mock if not configured."""
    model = _get_model()
    if model is None:
        return _mock_response(prompt)
    try:
        result = model.generate_text(prompt=prompt)
        return result
    except Exception as e:
        return f"[watsonx error: {e}]\n\n" + _mock_response(prompt)


def get_health() -> dict:
    """Check watsonx connectivity."""
    if not settings.WATSONX_API_KEY:
        return {
            "status": "not_configured",
            "model_id": settings.WATSONX_MODEL_ID,
            "message": "Set WATSONX_API_KEY and WATSONX_PROJECT_ID in .env to enable AI features",
        }
    model = _get_model()
    if model is None:
        return {"status": "error", "model_id": settings.WATSONX_MODEL_ID}
    try:
        details = model.get_details()
        return {
            "status": "connected",
            "model_id": details.get("model_id", settings.WATSONX_MODEL_ID),
            "provider": details.get("provider", "IBM"),
        }
    except Exception as e:
        return {"status": "error", "model_id": settings.WATSONX_MODEL_ID, "error": str(e)}


def _mock_response(prompt: str) -> str:
    """Return a clearly labelled mock response for demo / no-credential mode."""
    if "skill gap" in prompt.lower() or "hiring" in prompt.lower() or "capability" in prompt.lower():
        return (
            "[DEMO MODE — watsonx.ai not configured]\n\n"
            "**Skill Gap Recommendations:**\n"
            "1. Prioritize hiring 2 Senior Cloud Engineers with Kubernetes expertise (Expert level) "
            "to address the critical gap in the Platform team's upcoming migration project.\n"
            "2. Launch an internal upskilling programme for Salesforce developers — 4 existing "
            "employees are at Beginner level and could reach Intermediate within 2 sprints.\n"
            "3. Consider engaging a contract Security Architect for the Q3 compliance initiative "
            "while building internal capability through certifications."
        )
    elif "delivery" in prompt.lower() or "sprint" in prompt.lower() or "coach" in prompt.lower():
        return (
            "[DEMO MODE — watsonx.ai not configured]\n\n"
            "**Delivery Coaching Insights:**\n"
            "1. **Risk: Sprint over-commitment** — The squad's planned velocity exceeds historical "
            "average by 30%. Recommend reducing sprint scope by 20% and focusing on completing "
            "in-progress work before pulling new items.\n"
            "2. **Risk: Defect leakage trend** — 3 consecutive sprints show increasing defect "
            "leakage. Suggest introducing mandatory peer code review and shifting QA left by "
            "involving QA Engineers in sprint planning."
        )
    elif "risk" in prompt.lower() or "board" in prompt.lower() or "executive" in prompt.lower():
        return (
            "[DEMO MODE — watsonx.ai not configured]\n\n"
            "**Executive Risk Summary:**\n"
            "The enterprise delivery posture is currently Amber-rated, with the Integration and "
            "SAP teams showing elevated resource utilisation above 90% capacity. Three active "
            "projects face skill coverage gaps in cloud-native and security domains, posing "
            "moderate delivery risk in Q3. Immediate action is recommended on authorization "
            "compliance renewals — 12 production access credentials are expired across 4 teams."
        )
    return (
        "[DEMO MODE — watsonx.ai not configured]\n\n"
        "This response would be generated by IBM watsonx.ai using the "
        f"{settings.WATSONX_MODEL_ID} model. Configure WATSONX_API_KEY and "
        "WATSONX_PROJECT_ID in your .env file to enable live AI insights."
    )
